export default [ 
  { label: 'Afghanistan - +93' },
  { label: 'Albania - +355' },
  { label: 'Algeria - +213' },
  { label: 'American Samoa - +1684' },
  { label: 'Andorra - +376' },
  { label: 'Angola - +244' },
  { label: 'Anguilla - +1264' },
  { label: 'Antarctica - +672' },
  { label: 'Antigua and Barbuda - +1268' },
  { label: 'Argentina - +54' },
  { label: 'Armenia - +374' },
  { label: 'Aruba - +297' },
  { label: 'Australia - +61' },
  { label: 'Austria - +43' },
  { label: 'Azerbaijan - +994' },
  { label: 'Bahamas - +1242' },
  { label: 'Bahrain - +973' },
  { label: 'Bangladesh - +880' },
  { label: 'Barbados - +1246' },
  { label: 'Belarus - +375' },
  { label: 'Belgium - +32' },
  { label: 'Belize - +501' },
  { label: 'Benin - +229' },
  { label: 'Bermuda - +1441' },
  { label: 'Bhutan - +975' },
  { label: 'Bolivia - +591' },
  { label: 'Bosnia and Herzegovina - +387' },
  { label: 'Botswana - +267' },
  { label: 'Brazil - +55' },
  { label: 'British Indian Ocean Territory - +246' },
  { label: 'Brunei Darussalam - +673' },
  { label: 'Bulgaria - +359' },
  { label: 'Burkina Faso - +226' },
  { label: 'Burundi - +257' },
  { label: 'Cambodia - +855' },
  { label: 'Cameroon - +237' },
  { label: 'Canada - +1' },
  { label: 'Cape Verde - +238' },
  { label: 'Cayman Islands - + 345' },
  { label: 'Central African Republic - +236' },
  { label: 'Chad - +235' },
  { label: 'Chile - +56' },
  { label: 'China - +86' },
  { label: 'Colombia - +57' },
  { label: 'Comoros - +269' },
  { label: 'Congo - +242' },
  { label: 'DR Congo - +243' },
  { label: 'Cook Islands - +682' },
  { label: 'Costa Rica - +506' },
  { label: 'Cote d\'Ivoire - +225' },
  { label: 'Croatia - +385' },
  { label: 'Cuba - +53' },
  { label: 'Cyprus - +357' },
  { label: 'Czech Republic - +420' },
  { label: 'Denmark - +45' },
  { label: 'Djibouti - +253' },
  { label: 'Dominica - +1767' },
  { label: 'Dominican Republic - +1849' },
  { label: 'Ecuador - +593' },
  { label: 'Egypt - +20' },
  { label: 'El Salvador - +503' },
  { label: 'Equatorial Guinea - +240' },
  { label: 'Eritrea - +291' },
  { label: 'Estonia - +372' },
  { label: 'Ethiopia - +251' },
  { label: 'Faroe Islands - +298' },
  { label: 'Fiji - +679' },
  { label: 'Finland - +358' },
  { label: 'France - +33' },
  { label: 'French Guiana - +594' },
  { label: 'French Polynesia - +689' },
  { label: 'Gabon - +241' },
  { label: 'Gambia - +220' },
  { label: 'Georgia - +995' },
  { label: 'Germany - +49' },
  { label: 'Ghana - +233' },
  { label: 'Gibraltar - +350' },
  { label: 'Greece - +30' },
  { label: 'Greenland - +299' },
  { label: 'Grenada - +1473' },
  { label: 'Guadeloupe, Saint Martin, or Saint Barthelemy - +590' },
  { label: 'Guam - +1671' },
  { label: 'Guatemala - +502' },
  { label: 'Guinea - +224' },
  { label: 'Guinea-Bissau - +245' },
  { label: 'Haiti - +509' },
  { label: 'Vatican City State - +379' },
  { label: 'Honduras - +504' },
  { label: 'Hong Kong - +852' },
  { label: 'Hungary - +36' },
  { label: 'Iceland - +354' },
  { label: 'India - +91' },
  { label: 'Indonesia - +62' },
  { label: 'Iran - +98' },
  { label: 'Iraq - +964' },
  { label: 'Ireland - +353' },
  { label: 'Israel - +972' },
  { label: 'Italy - +39' },
  { label: 'Jamaica - +1876' },
  { label: 'Japan - +81' },
  { label: 'Jordan - +962' },
  { label: 'Kazakhstan - +77' },
  { label: 'Kenya - +254' },
  { label: 'Kiribati - +686' },
  { label: 'North Korea - +850' },
  { label: 'South Korea - +82' },
  { label: 'Kuwait - +965' },
  { label: 'Kyrgyzstan - +996' },
  { label: 'Laos - +856' },
  { label: 'Latvia - +371' },
  { label: 'Lebanon - +961' },
  { label: 'Lesotho - +266' },
  { label: 'Liberia - +231' },
  { label: 'Libyan Arab Jamahiriya - +218' },
  { label: 'Liechtenstein - +423' },
  { label: 'Lithuania - +370' },
  { label: 'Luxembourg - +352' },
  { label: 'Macao - +853' },
  { label: 'Macedonia - +389' },
  { label: 'Madagascar - +261' },
  { label: 'Malawi - +265' },
  { label: 'Malaysia - +60' },
  { label: 'Maldives - +960' },
  { label: 'Mali - +223' },
  { label: 'Malta - +356' },
  { label: 'Marshall Islands - +692' },
  { label: 'Martinique - +596' },
  { label: 'Mauritania - +222' },
  { label: 'Mauritius - +230' },
  { label: 'Mayotte or Reunion- +262' },
  { label: 'Mexico - +52' },
  { label: 'Micronesia - +691' },
  { label: 'Moldova - +373' },
  { label: 'Monaco - +377' },
  { label: 'Mongolia - +976' },
  { label: 'Montenegro - +382' },
  { label: 'Montserrat - +1664' },
  { label: 'Morocco - +212' },
  { label: 'Mozambique - +258' },
  { label: 'Myanmar - +95' },
  { label: 'Namibia - +264' },
  { label: 'Nauru - +674' },
  { label: 'Nepal - +977' },
  { label: 'Netherlands - +31' },
  { label: 'Netherlands Antilles - +599' },
  { label: 'New Caledonia - +687' },
  { label: 'New Zealand - +64' },
  { label: 'Nicaragua - +505' },
  { label: 'Niger - +227' },
  { label: 'Nigeria - +234' },
  { label: 'Niue - +683' },
  { label: 'Northern Mariana Islands - +1670' },
  { label: 'Norway - +47' },
  { label: 'Oman - +968' },
  { label: 'Pakistan - +92' },
  { label: 'Palau - +680' },
  { label: 'Palestinian Territory, Occupied - +970' },
  { label: 'Panama - +507' },
  { label: 'Papua New Guinea - +675' },
  { label: 'Paraguay or Guyana - +595' },
  { label: 'Peru - +51' },
  { label: 'Philippines - +63' },
  { label: 'Pitcairn - +872' },
  { label: 'Poland - +48' },
  { label: 'Portugal - +351' },
  { label: 'Puerto Rico - +1939' },
  { label: 'Qatar - +974' },
  { label: 'Romania - +40' },
  { label: 'Russia - +7' },
  { label: 'Rwanda - +250' },
  { label: 'Saint Helena, Ascension and Tristan Da Cunha - +290' },
  { label: 'Saint Kitts and Nevis - +1869' },
  { label: 'Saint Lucia - +1758' },
  { label: 'Saint Pierre and Miquelon - +508' },
  { label: 'Saint Vincent and the Grenadines - +1784' },
  { label: 'Samoa - +685' },
  { label: 'San Marino - +378' },
  { label: 'Sao Tome and Principe - +239' },
  { label: 'Saudi Arabia - +966' },
  { label: 'Senegal - +221' },
  { label: 'Serbia - +381' },
  { label: 'Seychelles - +248' },
  { label: 'Sierra Leone - +232' },
  { label: 'Singapore - +65' },
  { label: 'Slovakia - +421' },
  { label: 'Slovenia - +386' },
  { label: 'Solomon Islands - +677' },
  { label: 'Somalia - +252' },
  { label: 'South Africa - +27' },
  { label: 'South Sudan - +211' },
  { label: 'Falkland Islands or South Georgia and the South Sandwich Islands - +500' },
  { label: 'Spain - +34' },
  { label: 'Sri Lanka - +94' },
  { label: 'Sudan - +249' },
  { label: 'SuritextKey - +597' },
  { label: 'Swaziland - +268' },
  { label: 'Sweden - +46' },
  { label: 'Switzerland - +41' },
  { label: 'Syrian Arab Republic - +963' },
  { label: 'Taiwan - +886' },
  { label: 'Tajikistan - +992' },
  { label: 'Tanzania - +255' },
  { label: 'Thailand - +66' },
  { label: 'Timor-Leste - +670' },
  { label: 'Togo - +228' },
  { label: 'Tokelau - +690' },
  { label: 'Tonga - +676' },
  { label: 'Trinidad and Tobago - +1868' },
  { label: 'Tunisia - +216' },
  { label: 'Turkey - +90' },
  { label: 'Turkmenistan - +993' },
  { label: 'Turks and Caicos Islands - +1649' },
  { label: 'Tuvalu - +688' },
  { label: 'Uganda - +256' },
  { label: 'Ukraine - +380' },
  { label: 'United Arab Emirates - +971' },
  { label: 'United Kingdom - +44' },
  { label: 'United States - +1'},
  { label: 'USA - +1' },
  { label: 'Uruguay - +598' },
  { label: 'Uzbekistan - +998' },
  { label: 'Vanuatu - +678' },
  { label: 'Venezuela - +58' },
  { label: 'Vietnam - +84' },
  { label: 'Virgin Islands, British - +1284' },
  { label: 'Virgin Islands, U.S. - +1340' },
  { label: 'Wallis and Futuna - +681' },
  { label: 'Yemen - +967' },
  { label: 'Zambia - +260' },
  { label: 'Zimbabwe - +263' }
];
